### ISSUE TITLE
An unexpected error has occurred with osprey (version 0.1a)

### ISSUE THREAD

**Issue by dendisuhubdy** [cxhernandez/molencoder#3]
```
(dl3) dendisuhubdy@grok-machine:~/data$ molencoder train --dataset molecules/chembl22.h5 --cuda
Epoch 0:
t = 100, loss = 0.0532
t = 200, loss = 0.0467
t = 300, loss = 0.0473
t = 400, loss = 0.0473
t = 500, loss = 0.0468
t = 600, loss = 0.0469
t = 700, loss = 0.0467
t = 800, loss = 0.0474
t = 900, loss = 0.0470
t = 1000, loss = 0.0456
t = 1100, loss = 0.0481
t = 1200, loss = 0.0443
t = 1300, loss = 0.0485
t = 1400, loss = 0.0474
t = 1500, loss = 0.0465
t = 1600, loss = 0.0469
t = 1700, loss = 0.0460
t = 1800, loss = 0.0453
t = 1900, loss = 0.0476
t = 2000, loss = 0.0466
t = 2100, loss = 0.0454
t = 2200, loss = 0.0471
t = 2300, loss = 0.0462
t = 2400, loss = 0.0458
t = 2500, loss = 0.0464
t = 2600, loss = 0.0475
t = 2700, loss = 0.0474
t = 2800, loss = 0.0442
t = 2900, loss = 0.0463
t = 3000, loss = 0.0455
t = 3100, loss = 0.0458
t = 3200, loss = 0.0457
t = 3300, loss = 0.0470
t = 3400, loss = 0.0467
t = 3500, loss = 0.0450
t = 3600, loss = 0.0473
t = 3700, loss = 0.0471
t = 3800, loss = 0.0471
t = 3900, loss = 0.0461
t = 4000, loss = 0.0497
An unexpected error has occurred with osprey (version 0.1a), please
consider sending the following traceback to the osprey GitHub issue tracker at:
        https://github.com/cxhernandez/molencoder/issues

Traceback (most recent call last):
  File "/u/suhubdyd/.conda/envs/dl3/bin/molencoder", line 11, in <module>
    load_entry_point('molencoder==0.1a0', 'console_scripts', 'molencoder')()
  File "/u/suhubdyd/.conda/envs/dl3/lib/python3.6/site-packages/molencoder-0.1a0-py3.6.egg/molencoder/cli/main.py", line 33, in main
  File "/u/suhubdyd/.conda/envs/dl3/lib/python3.6/site-packages/molencoder-0.1a0-py3.6.egg/molencoder/cli/main.py", line 38, in args_func
  File "/u/suhubdyd/.conda/envs/dl3/lib/python3.6/site-packages/molencoder-0.1a0-py3.6.egg/molencoder/cli/parser_train.py", line 55, in func
  File "/u/suhubdyd/.conda/envs/dl3/lib/python3.6/site-packages/molencoder-0.1a0-py3.6.egg/molencoder/utils.py", line 89, in validate_model
ValueError: too many values to unpack (expected 2)
```

**Comment by cxhernandez** [comment]
This was a bug from a [few commits ago](https://github.com/cxhernandez/molencoder/blame/4c7bbf1d6c31a531538b4b5a71799587f1897b03/molencoder/utils.py#L63). Should be fixed now in master! Sorry about that!

**Comment by dendisuhubdy** [comment]
@cxhernandez no problem! Thanks!
